package com.coditramuntana.musicrecords.config;

import com.coditramuntana.musicrecords.model.data.Artist;
import com.coditramuntana.musicrecords.model.data.Lp;
import com.coditramuntana.musicrecords.model.data.Song;
import com.coditramuntana.musicrecords.repository.ArtistRepository;
import com.coditramuntana.musicrecords.repository.LpRepository;
import com.coditramuntana.musicrecords.service.AuthorService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Loads the sample discography the first time the application starts.
 *
 * <p>Implemented in Java rather than as a {@code data.sql} script for three reasons: the
 * SQLite database file survives restarts, so seeding must be idempotent; identifiers are
 * generated by the database, so a script would need hardcoded ids for the join table; and
 * reusing {@link AuthorService} guarantees the seed exercises the very same
 * "reuse the author if it already exists" logic as the API.
 *
 * <p>LPs are saved explicitly instead of cascading from the artist: the artist to LP
 * association is deliberately declared without cascade so that deleting an artist can
 * never wipe out a whole discography.
 */
@Slf4j
@Component
@RequiredArgsConstructor
@ConditionalOnProperty(name = "app.seeding.enabled", havingValue = "true", matchIfMissing = true)
public class DataSeeder implements ApplicationRunner {

    private final ArtistRepository artistRepository;
    private final LpRepository lpRepository;
    private final AuthorService authorService;

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        if (artistRepository.count() > 0) {
            log.info("Database already contains data, skipping seeding");
            return;
        }

        log.info("Seeding database with the sample discography");

        seedMetallica();
        seedSepultura();
        seedPinkFloyd();
        seedIronMaiden();
        seedNirvana();
        seedRadiohead();

        log.info("Seeding completed: {} artists and {} LPs created",
                artistRepository.count(), lpRepository.count());
    }

    /**
     * The example given in the assignment, plus a second LP so the artist detail page
     * shows an LP count greater than one.
     */
    private void seedMetallica() {
        Artist metallica = saveArtist("Metallica",
                "American heavy metal band formed in Los Angeles in 1981.");

        saveLp(metallica, "Black album", "Fifth studio album, released in 1991.", List.of(
                song("My Friend of Misery", "Hetfield", "Jason N."),
                song("Enter Sandman", "Hetfield"),
                song("Unforgiven", "Hetfield", "Hammett")));

        saveLp(metallica, "Ride the Lightning", "Second studio album, released in 1984.", List.of(
                song("Fade to Black", "Hetfield", "Ulrich"),
                song("Creeping Death", "Hetfield", "Hammett")));
    }

    /**
     * The second example of the assignment. It shares an author with Metallica, which is
     * what makes the many-to-many association visible in the report.
     */
    private void seedSepultura() {
        Artist sepultura = saveArtist("Sepultura",
                "Brazilian heavy metal band formed in Belo Horizonte in 1984.");

        saveLp(sepultura, "Against", "Seventh studio album, released in 1998.", List.of(
                song("Hatred Aside", "Jason N.")));
    }

    private void seedPinkFloyd() {
        Artist pinkFloyd = saveArtist("Pink Floyd",
                "English rock band formed in London in 1965.");

        saveLp(pinkFloyd, "The Dark Side of the Moon", "Eighth studio album, released in 1973.", List.of(
                song("Time", "Waters", "Gilmour", "Wright", "Mason"),
                song("Money", "Waters")));
    }

    /**
     * Includes an LP without songs on purpose: it must still appear in the report with a
     * song count of zero and no authors.
     */
    private void seedIronMaiden() {
        Artist ironMaiden = saveArtist("Iron Maiden",
                "English heavy metal band formed in Leyton in 1975.");

        saveLp(ironMaiden, "The Number of the Beast", "Third studio album, released in 1982.", List.of(
                song("Run to the Hills", "Harris"),
                song("Hallowed Be Thy Name", "Harris")));

        saveLp(ironMaiden, "Piece of Mind", "Fourth studio album, released in 1983.", List.of());
    }

    private void seedNirvana() {
        Artist nirvana = saveArtist("Nirvana",
                "American rock band formed in Aberdeen, Washington, in 1987.");

        saveLp(nirvana, "Nevermind", "Second studio album, released in 1991.", List.of(
                song("Smells Like Teen Spirit", "Cobain", "Novoselic", "Grohl"),
                song("Come as You Are", "Cobain")));
    }

    /**
     * Deliberately seeded without LPs, so the artist detail page can be checked with a
     * count of zero and the artist can be deleted without hitting the conflict rule.
     */
    private void seedRadiohead() {
        saveArtist("Radiohead", "English rock band formed in Abingdon-on-Thames in 1985.");
    }

    private Artist saveArtist(String name, String description) {
        return artistRepository.save(Artist.builder()
                .name(name)
                .description(description)
                .build());
    }

    private void saveLp(Artist artist, String name, String description, List<SongSpec> songs) {
        Lp lp = Lp.builder()
                .name(name)
                .description(description)
                .artist(artist)
                .build();

        songs.forEach(spec -> {
            Song song = Song.builder().name(spec.name()).build();
            song.replaceAuthors(authorService.resolveOrCreate(spec.authorNames()));
            lp.addSong(song);
        });

        lpRepository.save(lp);
    }

    private SongSpec song(String name, String... authorNames) {
        return new SongSpec(name, List.of(authorNames));
    }

    /**
     * Declarative description of a song and its authors, used only while seeding.
     */
    private record SongSpec(String name, List<String> authorNames) {
    }

}
